### ISSUE TITLE
Publish a new version with the new license?

### ISSUE THREAD

**Issue by dangoor** [tecfu/breakword#18]
Can you publish an updated version with the new license? No other change required. It's just that the existing package up on npm has the GPL license in it.

**Comment by vmizg** [comment]
+1

This is being used by as a nested dependency for @changesets/cli -> tty-table -> smartwrap -> breakword in our repository and we're sorting out the top level license. It looks like you are explicit about it being MIT in 1.0.5, but it's not reflected in the published package in npm.

**Comment by tecfu** [comment]
Published [breakword@1.0.6](https://www.npmjs.com/package/breakword/v/1.0.6).

**Comment by ghost** [comment]
Thank you!
